### ISSUE TITLE
doens't work with immutable.js state

### ISSUE THREAD

**Issue by koddo** [DJCordhose/redux-title#1]
Thanks for awesome lib.
Sadly, it currently doesn't work with `immutable.js` state, but that's easy to fix.
There are six occurrences of `getState().title`. I changed them to `getState().get('title')` and everything worked like a charm.
I found the `redux-form` works both without and with the `immutable.js`, we can use either `import { reduxForm } from 'redux-form'` or `from 'redux-form/immutable'`.
What about this way?

**Comment by DJCordhose** [comment]
Hm, right, I am making assumptions on how your store should look like. Not good.

I guess I will refactor a bit and make it configurable how to get and set the state to the store. Will also provide an example on how to use it with immutable.js. 

Stay tuned

In the meantime: What is your store layout like? A single immutable map?

**Comment by DJCordhose** [comment]
Made a tiny change to https://github.com/DJCordhose/redux-title/blob/master/src/index.js` so that you can provide a custom function to get the title out of the state (also one to set the title to state, just in case).

In https://github.com/DJCordhose/redux-title/blob/master/test/immutable.karma.js I show how to make `redux-immutable` work with this, but it should be really easy to use it with any other store implementation or any other immutable approach. 

Important piece of code:

``` javascript
        const initialState = Immutable.Map();
        const rootReducer = combineReducers({
            title: titleReducer
        });
        store = createStore(rootReducer, initialState);
        const getTitle = () => store.getState().get('title');
        unsubscribe = syncReduxAndTitle(store, getTitle);
```

Does this solve your problem? If so I will publish this new version to npm...

**Comment by koddo** [comment]
Sorry for a delay.
Great. I've only changed `syncReduxAndTitle(store)` to `syncReduxAndTitle(store, () => store.getState().get('title'))` in my code and everything works perfecly now. Thank you!

**Comment by DJCordhose** [comment]
Great, pushed version 0.0.3 to npm
